
services:
  public:
    build: ./public
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    volumes:
      # The same volume can be shared with other services
       - ./public:/usr/share/nginx/html
    networks:
     - nodeapp

  backend:
    build: ./Backend
    container_name: nodeapp
    ports:
      - "5050:5050"
    depends_on:
      - mongo

    restart: always
    volumes:
      # The same volume can be shared with other services
      - ./Backend:/app
    networks:
     - nodeapp

  mongo:
    build: ./Database/Mongo
    container_name: mongo
    ports:
      - "27017:27017"
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    
    restart: always
    volumes:
      # The same volume can be shared with other services
      - mongovolume:/data/db
    networks:
       - nodeapp

  mongo-express:
    build: ./Database/Mongo-Express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: qwerty
    
    depends_on:
      - mongo
    restart: always
    
    networks:
     - nodeapp
networks:
  nodeapp:
    driver: bridge
volumes:
      # The same volume can be shared with other services
       mongovolume:
       publicvolume:
       backendvolume: